version: 3

pullapprove_conditions:
- "'WIP' not in title"  # only review if not marked as work in progress
- "'wip' not in labels"  # let hotfix PRs go through without review
- "'*circleci*' in statuses.successful"  # only review if tests have already passed
- "'*codecov*' in statuses.successful"  # only review if tests have already passed
- "'*danger*' in statuses.successful"  # only review if danger have already passed
- "base == 'master'"
- "base == 'release-prd'"
- "base == 'release-stg'"
- "base == 'develop'"
- "not mergeable"

notifications:
- when: pull_request.opened
  comment: "こんにちは、@{{ author }}さん、テスト通るか確認してね！終わったら、レビューするよ！"
- when: pullapprove.approved
  comment: "レビュー終わったよ！@{{ author }}さん、ありがとう！あとはmergeしよう！"
- when: pullapprove.review_requested
  comment: "@{{ requested_reviewers }}さん、レビューお願いします:bow:"

groups:
  code:
    reviews:
      required: 1  # 3 approvals from this group are required
      request_order: shuffle  # reviewers will be chosen in a random order
      author_value: 1  # if the PR author is in this group, automatically add +1
