name: create release pr
on:
  push:
    branches:
      - develop
      - release-stg
      - release-stg01
      - release-prd
jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: check if develop_pr_exists
        id: check_dev_to_stg
        if: ${{ github.ref_name == 'develop' }}
        run: echo "::set-output name=count::$(gh pr list -B release-stg -H develop | wc -l)"
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: create dev to stg pr
        if: ${{ github.ref_name == 'develop' && steps.check_dev_to_stg.outputs.count == 0 }}
        run: gh pr create -B "release-stg" -H "develop" -l STG -t "dev to stg" -b ""
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: check if stg_pr_exists
        id: check_stg_to_stg01
        if: ${{ github.ref_name == 'release-stg' }}
        run: echo "::set-output name=count::$(gh pr list -B release-stg01 -H release-stg | wc -l)"
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: create stg to stg01 pr
        if: ${{ github.ref_name == 'release-stg' && steps.check_stg_to_stg01.outputs.count == 0 }}
        run: gh pr create -B "release-stg01" -H "release-stg" -l UT -t "stg to stg01" -b ""
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: check if stg01_pr_exists
        id: check_stg01_to_prd
        if: ${{ github.ref_name == 'release-stg01' }}
        run: echo "::set-output name=count::$(gh pr list -B release-prd -H release-stg01 | wc -l)"
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: create stg01 to prd pr
        if: ${{ github.ref_name == 'release-stg01' && steps.check_stg01_to_prd.outputs.count == 0 }}
        run: gh pr create -d -B "release-prd" -H "release-stg01" -l PRD -t "stg01 to prd" -b ""
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: check if prd_pr_exists
        id: check_prd_to_dev
        if: ${{ github.ref_name == 'release-prd' }}
        run: echo "::set-output name=count::$(gh pr list -B develop -H release-prd | wc -l)"
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
      - name: create prd to dev pr
        if: ${{ github.ref_name == 'release-prd' && steps.check_prd_to_dev.outputs.count == 0 }}
        run: gh pr create -B "develop" -H "release-prd" -l dev -t "prd to dev" -b ""
        env:
          GH_TOKEN: ${{ secrets.BUNDLE_GITHUB__COM }}
