name: Cycle PR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - develop_sprint*
      - integration/sprint*
      - release-*

jobs:
  cycle-pr:
    permissions:
      contents: read
      pull-requests: write
    uses: f-scratch/.github/.github/workflows/cycle-pr.yml@master
